# Generated by Django 4.1.5 on 2023-01-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_answers_user_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
    ]
