# Generated by Django 4.1.5 on 2023-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, default='0', max_length=25)),
                ('payment', models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=25)),
                ('reference_number', models.CharField(max_length=30)),
                ('reference_url', models.CharField(max_length=255)),
            ],
        ),
    ]
