# Generated by Django 4.1.5 on 2023-01-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_order_ticket_ticketdetail_orderdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
