# Generated by Django 4.1.5 on 2023-02-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_place',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
