# Generated by Django 4.1.5 on 2023-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_address_order_delivery_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
