# Generated by Django 4.1.5 on 2023-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_order_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('on_delivery', 'On Delivery'), ('online_payment', 'Online Payment')], default='on_delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
