# Generated by Django 4.1.5 on 2023-02-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_order_deleted_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='items',
            new_name='item',
        ),
    ]
