# Generated by Django 4.1.5 on 2023-02-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_rename_items_orderdetail_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food.item'),
        ),
    ]
