# Generated by Django 4.1.5 on 2023-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_order_payment_detail_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
